#include <glsl-processor/logging.h>
#include <glsl-processor/memoryalloc.h>
#include <glsl-processor/ast.h>
#include <stdio.h>


#ifdef _MSC_VER
#include <Windows.h>
static void make_directory_if_not_exists(const char *dirpath)
{
        BOOL ret = CreateDirectory(dirpath, NULL);
        if (!ret && GetLastError() != ERROR_ALREADY_EXISTS)
                fatal_f("Failed to create directory %s", dirpath);
}
#else
#include <sys/stat.h>
#include <sys/types.h>
#include <errno.h>
static void make_directory_if_not_exists(const char *dirpath)
{
        int r = mkdir(dirpath, 0770);
        if (r == -1 && errno != EEXIST)
                fatal_f("Failed to create directory %s: %s",
                        dirpath, strerror(errno));
}
#endif

// TODO
#define AUTOGENERATED_DIR "autogenerated/"
#define IFACE_C_FILEPATH AUTOGENERATED_DIR "shaders.c"
#define IFACE_H_FILEPATH AUTOGENERATED_DIR "shaders.h"

#define INDENT "        "

struct MtsCtx {
        struct Ast *ast;
        FILE *hFileHandle;
        FILE *cFileHandle;
};

static FILE *create_or_truncate_file_and_open_for_writing(const char *filepath)
{
        FILE *f = fopen(filepath, "wb");
        if (f == NULL)
                fatal_f("failed to open file for writing: %s", filepath);
        return f;
}

struct LinkedShaderIterator {
        struct Ast *ast;
        int programIndex;
        int linkIndex;
};

static void begin_iterating_linked_shaders(struct LinkedShaderIterator *iter, struct Ast *ast, int programIndex)
{
        iter->ast = ast;
        iter->programIndex = programIndex;
        iter->linkIndex = 0;
        while (iter->linkIndex < ast->numLinkItems && ast->linkItems[iter->linkIndex].resolvedProgramIndex != programIndex)
                iter->linkIndex++;
}

static int have_linked_shader(struct LinkedShaderIterator *iter)
{
        return iter->linkIndex < iter->ast->numLinkItems;
}

static void go_to_next_linked_shader(struct LinkedShaderIterator *iter)
{
        ENSURE(iter->linkIndex < iter->ast->numLinkItems);
        iter->linkIndex++;
        while (iter->linkIndex < iter->ast->numLinkItems && iter->ast->linkItems[iter->linkIndex].resolvedProgramIndex != iter->programIndex)
                iter->linkIndex++;
}

static int get_linked_shader(struct LinkedShaderIterator *iter)
{
        ENSURE(iter->linkIndex < iter->ast->numLinkItems);
        return iter->ast->linkItems[iter->linkIndex].resolvedShaderIndex;
}

struct UniformIterator {
        struct LinkedShaderIterator shaderIter;
        struct Ast *ast;
        struct ShaderfileAst *fa;
        int toplevelNodeIndex;
};

static int have_uniform(struct UniformIterator *iter)
{
        if (iter->fa != NULL) {
                ENSURE(iter->toplevelNodeIndex < iter->fa->numToplevelNodes);
                ENSURE(iter->fa->toplevelNodes[iter->toplevelNodeIndex]->directiveKind == DIRECTIVE_UNIFORM);
        }
        return iter->fa != NULL;
}

static void go_to_next_uniform(struct UniformIterator *iter)
{
        ENSURE(iter->fa != NULL);  // because we shouldn't be called otherwise
        ENSURE(iter->toplevelNodeIndex < iter->fa->numToplevelNodes);  // because, if iter->fa != NULL, the toplevelNodeIndex should be valid.
        iter->toplevelNodeIndex++;
        for (;;) {
                while (iter->toplevelNodeIndex < iter->fa->numToplevelNodes && iter->fa->toplevelNodes[iter->toplevelNodeIndex]->directiveKind != DIRECTIVE_UNIFORM)
                        iter->toplevelNodeIndex++;
                if (iter->toplevelNodeIndex < iter->fa->numToplevelNodes)
                        break;
                go_to_next_linked_shader(&iter->shaderIter);
                if (!have_linked_shader(&iter->shaderIter)) {
                        iter->fa = NULL;
                        break;
                }
                int shaderIndex = get_linked_shader(&iter->shaderIter);
                iter->fa = &iter->ast->shaderfileAsts[shaderIndex];
                iter->toplevelNodeIndex = 0;
        }
}

static void begin_iterating_uniforms(struct UniformIterator *iter, struct Ast *ast, int programIndex)
{
        begin_iterating_linked_shaders(&iter->shaderIter, ast, programIndex);
        iter->ast = ast;
        iter->fa = NULL;
        iter->toplevelNodeIndex = -1337;
        if (have_linked_shader(&iter->shaderIter)) {
                int shaderIndex = get_linked_shader(&iter->shaderIter);
                iter->fa = &iter->ast->shaderfileAsts[shaderIndex];
                iter->toplevelNodeIndex = 0;
                // code to find first uniform.
                // very ugly code, trying to avoid duplication. There must be a better way
                if (iter->toplevelNodeIndex == iter->fa->numToplevelNodes
                        || iter->fa->toplevelNodes[iter->toplevelNodeIndex]->directiveKind != DIRECTIVE_UNIFORM)
                        go_to_next_uniform(iter);
        }
}

static struct UniformDecl *get_uniform(struct UniformIterator *iter)
{
        ENSURE(have_uniform(iter));
        return iter->fa->toplevelNodes[iter->toplevelNodeIndex]->data.tUniform;
}



struct VariableIterator {
        struct LinkedShaderIterator shaderIter;
        struct Ast *ast;
        struct ShaderfileAst *fa;
        int toplevelNodeIndex;
};

static int have_variable(struct VariableIterator *iter)
{
        if (iter->fa != NULL) {
                ENSURE(iter->toplevelNodeIndex < iter->fa->numToplevelNodes);
                ENSURE(iter->fa->toplevelNodes[iter->toplevelNodeIndex]->directiveKind == DIRECTIVE_VARIABLE);
        }
        return iter->fa != NULL;
}

static void go_to_next_variable(struct VariableIterator *iter)
{
        ENSURE(iter->fa != NULL);  // because we shouldn't be called otherwise
        ENSURE(iter->toplevelNodeIndex < iter->fa->numToplevelNodes);  // because, if iter->fa != NULL, the toplevelNodeIndex should be valid.
        iter->toplevelNodeIndex++;
        for (;;) {
                while (iter->toplevelNodeIndex < iter->fa->numToplevelNodes && iter->fa->toplevelNodes[iter->toplevelNodeIndex]->directiveKind != DIRECTIVE_VARIABLE)
                        iter->toplevelNodeIndex++;
                if (iter->toplevelNodeIndex < iter->fa->numToplevelNodes)
                        break;
                go_to_next_linked_shader(&iter->shaderIter);
                if (!have_linked_shader(&iter->shaderIter)) {
                        iter->fa = NULL;
                        break;
                }
                int shaderIndex = get_linked_shader(&iter->shaderIter);
                iter->fa = &iter->ast->shaderfileAsts[shaderIndex];
                iter->toplevelNodeIndex = 0;
        }
}

static void begin_iterating_variables(struct VariableIterator *iter, struct Ast *ast, int programIndex)
{
        begin_iterating_linked_shaders(&iter->shaderIter, ast, programIndex);
        iter->ast = ast;
        iter->fa = NULL;
        iter->toplevelNodeIndex = -1337;
        if (have_linked_shader(&iter->shaderIter)) {
                int shaderIndex = get_linked_shader(&iter->shaderIter);
                iter->fa = &iter->ast->shaderfileAsts[shaderIndex];
                iter->toplevelNodeIndex = 0;
                // code to find first uniform.
                // very ugly code, trying to avoid duplication. There must be a better way
                if (iter->toplevelNodeIndex == iter->fa->numToplevelNodes
                        || iter->fa->toplevelNodes[iter->toplevelNodeIndex]->directiveKind != DIRECTIVE_VARIABLE)
                        go_to_next_variable(iter);
        }
}

static struct VariableDecl *get_variable(struct VariableIterator *iter)
{
        ENSURE(have_variable(iter));
        return iter->fa->toplevelNodes[iter->toplevelNodeIndex]->data.tVariable;
}



static void begin_enum(struct MtsCtx *ctx)
{
        fprintf(ctx->hFileHandle, "enum {\n");
}

static void end_enum(struct MtsCtx *ctx)
{
        fprintf(ctx->hFileHandle, "};\n\n");
}

static void add_enum_item(struct MtsCtx *ctx, const char *name1)
{
        fprintf(ctx->hFileHandle, INDENT "%s,\n", name1);
}

static void add_enum_item_2(struct MtsCtx *ctx, const char *name1, const char *name2)
{
        fprintf(ctx->hFileHandle, INDENT "%s_%s,\n", name1, name2);
}

static void add_enum_item_3(struct MtsCtx *ctx, const char *name1, const char *name2, const char *name3)
{
        fprintf(ctx->hFileHandle, INDENT "%s_%s_%s,\n", name1, name2, name3);
}

static void add_enum_item_AstString(struct MtsCtx *ctx, const char *enumPrefix, AstString astString)
{
        add_enum_item_2(ctx, enumPrefix, get_aststring_buffer(ctx->ast, astString));
}

static const char *const PRIMTYPE_to_GRAFIKATTRIBUTETYPE[NUM_PRIMTYPE_KINDS] = {
        [PRIMTYPE_FLOAT] = "GRAFIKATTRTYPE_FLOAT",
        [PRIMTYPE_VEC2] = "GRAFIKATTRTYPE_VEC2",
        [PRIMTYPE_VEC3] = "GRAFIKATTRTYPE_VEC3",
        [PRIMTYPE_VEC4] = "GRAFIKATTRTYPE_VEC4",
};

static const char *const PRIMTYPE_to_GRAFIKUNIFORMTYPE[NUM_PRIMTYPE_KINDS] = {
        [PRIMTYPE_FLOAT] = "GRAFIKUNIFORMTYPE_FLOAT",
        [PRIMTYPE_VEC2] = "GRAFIKUNIFORMTYPE_VEC2",
        [PRIMTYPE_VEC3] = "GRAFIKUNIFORMTYPE_VEC3",
        [PRIMTYPE_VEC4] = "GRAFIKUNIFORMTYPE_VEC4",
        [PRIMTYPE_MAT2] = "GRAFIKUNIFORMTYPE_MAT2",
        [PRIMTYPE_MAT3] = "GRAFIKUNIFORMTYPE_MAT3",
        [PRIMTYPE_MAT4] = "GRAFIKUNIFORMTYPE_MAT4",
};

void process_mts(struct Ast *ast)
{
        make_directory_if_not_exists(AUTOGENERATED_DIR);
        struct MtsCtx mtsCtx = { 0 };
        struct MtsCtx *ctx = &mtsCtx;
        ctx->ast = ast;
        ctx->cFileHandle = create_or_truncate_file_and_open_for_writing(IFACE_C_FILEPATH);
        ctx->hFileHandle = create_or_truncate_file_and_open_for_writing(IFACE_H_FILEPATH);

        fprintf(ctx->hFileHandle,
                "#ifndef AUTOGENERATED_SHADERS_H_INCLUDED\n"
                "#define AUTOGENERATED_SHADERS_H_INCLUDED\n"
                "\n"
                "#include <GLshadermanager/GLshadermanager.h>\n"
                "#include <WrapGL/WrapGL.h>\n"
                "\n"
                "#ifdef __cplusplus\n"
                "extern \"C\" {\n"
                "#endif\n"
                "\n");

        begin_enum(ctx);
        for (int i = 0; i < ast->numPrograms; i++)
                add_enum_item_AstString(ctx, "PROGRAM", ast->programDecls[i].programName);
        add_enum_item(ctx, "NUM_PROGRAM_KINDS");
        end_enum(ctx);

        begin_enum(ctx);
        for (int i = 0; i < ast->numShaders; i++)
                add_enum_item_AstString(ctx, "SHADER", ast->shaderDecls[i].shaderName);
        add_enum_item(ctx, "NUM_SHADER_KINDS");
        end_enum(ctx);

        //XXX: too much code here
        begin_enum(ctx);
        for (int programIndex = 0; programIndex < ast->numPrograms; programIndex++) {
                const char *programName = get_aststring_buffer(ast, ast->programDecls[programIndex].programName);
                struct UniformIterator uniformIter;
                for (begin_iterating_uniforms(&uniformIter, ast, programIndex);
                        have_uniform(&uniformIter); go_to_next_uniform(&uniformIter))
                {
                        struct UniformDecl *decl = get_uniform(&uniformIter);
                        const char *uniformName = get_aststring_buffer(ast, decl->uniDeclName);
                        add_enum_item_3(ctx, "UNIFORM", programName, uniformName);
                }
        }
        add_enum_item(ctx, "NUM_UNIFORM_KINDS");
        end_enum(ctx);

        //XXX: too much code here
        begin_enum(ctx);
        for (int programIndex = 0; programIndex < ast->numPrograms; programIndex++) {
                const char *programName = get_aststring_buffer(ast, ast->programDecls[programIndex].programName);
                struct VariableIterator variableIter;
                for (begin_iterating_variables(&variableIter, ast, programIndex);
                        have_variable(&variableIter); go_to_next_variable(&variableIter))
                {
                        struct VariableDecl *decl = get_variable(&variableIter);
                        if (decl->inOrOut != 0) /* TODO: enum for this. 0 == IN direction */
                                continue;
                        { // this code is too complex. It should be easier to determine the shader type.
                                int shaderIndex = ast->linkItems[variableIter.shaderIter.linkIndex].resolvedShaderIndex;
                                int shaderType = ast->shaderDecls[shaderIndex].shaderType;
                                if (shaderType != SHADERTYPE_VERTEX)
                                        continue;  // only vertex shaders can contain attributes. Attributes are "in" variables of the vertex shader.
                        }
                        const char *attribName = get_aststring_buffer(ast, decl->name);
                        add_enum_item_3(ctx, "ATTRIBUTE", programName, attribName);
                }
        }
        add_enum_item(ctx, "NUM_ATTRIBUTE_KINDS");
        end_enum(ctx);

        fprintf(ctx->hFileHandle,
                "extern const struct SM_ShaderInfo smShaderInfo[NUM_SHADER_KINDS];\n"
                "extern const struct SM_ProgramInfo smProgramInfo[NUM_PROGRAM_KINDS];\n"
                "extern const struct SM_LinkInfo smLinkInfo[];\n"
                "extern const int numLinkInfos;\n"
                "extern const struct SM_UniformInfo smUniformInfo[NUM_UNIFORM_KINDS];\n"
                "extern const struct SM_AttributeInfo smAttributeInfo[NUM_ATTRIBUTE_KINDS];\n"
                "extern const struct SM_Description smDescription;\n"
                "\n"
        );

        fprintf(ctx->cFileHandle, "#include <shaders.h>\n\n");

        fprintf(ctx->cFileHandle, "const struct SM_ProgramInfo smProgramInfo[NUM_PROGRAM_KINDS] = {\n");
        for (int i = 0; i < ast->numPrograms; i++) {
                const char *programName = get_aststring_buffer(ast, ast->programDecls[i].programName);
                fprintf(ctx->cFileHandle, INDENT "[PROGRAM_%s] = \"PROGRAM_%s\",\n", programName, programName);
        }
        fprintf(ctx->cFileHandle, "};\n\n");

        fprintf(ctx->cFileHandle, "const struct SM_ShaderInfo smShaderInfo[NUM_SHADER_KINDS] = {\n");
        for (int i = 0; i < ast->numShaders; i++) {
                struct ShaderDecl *decl = &ast->shaderDecls[i];
                const char *shaderName = get_aststring_buffer(ast, decl->shaderName);
                const char *shaderFilepath = get_aststring_buffer(ast, decl->shaderFilepath);
                static const char *const basePath = "Q:/src/PROJEKT_WIN/utilities/GrafikWindow/"; //XXX
                char *fullyQualifiedFilepath;
                ALLOC_MEMORY(&fullyQualifiedFilepath, strlen(basePath) + strlen(shaderFilepath) + 1);
                memcpy(fullyQualifiedFilepath, basePath, strlen(basePath));
                memcpy(fullyQualifiedFilepath + strlen(basePath), shaderFilepath, strlen(shaderFilepath) + 1);
                int shaderTypeKind = decl->shaderType;
                fprintf(ctx->cFileHandle, INDENT "[SHADER_%s] = { %s, \"SHADER_%s\", \"%s\" },\n",
                        shaderName, shadertypeKindString[shaderTypeKind], shaderName, fullyQualifiedFilepath);
                FREE_MEMORY(&fullyQualifiedFilepath);
        }
        fprintf(ctx->cFileHandle, "};\n\n");
        
        fprintf(ctx->cFileHandle, "const struct SM_LinkInfo smLinkInfo[] = {\n");
        for (int i = 0; i < ast->numLinkItems; i++) {
                //int programIndex = ast->linkItems[i].resolvedProgramIndex;
                //int shaderIndex = ast->linkItems[i].resolvedShaderIndex;
                const char *programName = get_aststring_buffer(ast, ast->linkItems[i].programName);
                const char *shaderName = get_aststring_buffer(ast, ast->linkItems[i].shaderName);
                fprintf(ctx->cFileHandle, INDENT "{ PROGRAM_%s, SHADER_%s },\n", programName, shaderName);
        }
        fprintf(ctx->cFileHandle, "};\n\n");

        fprintf(ctx->cFileHandle, "const struct SM_UniformInfo smUniformInfo[NUM_UNIFORM_KINDS] = {\n");
        for (int programIndex = 0; programIndex < ast->numPrograms; programIndex++) {
                const char *programName = get_aststring_buffer(ast, ast->programDecls[programIndex].programName);
                struct UniformIterator uniformIter;
                for (begin_iterating_uniforms(&uniformIter, ast, programIndex);
                        have_uniform(&uniformIter); go_to_next_uniform(&uniformIter))
                {
                        struct UniformDecl *decl = get_uniform(&uniformIter);
                        const char *uniformName = get_aststring_buffer(ast, decl->uniDeclName);
                        int primtypeKind = decl->uniDeclTypeExpr->primtypeKind;  //XXX depending on complicated data structure and bad design. There are no "type exprs"
                        const char *typeName = PRIMTYPE_to_GRAFIKUNIFORMTYPE[primtypeKind];
                        ENSURE(typeName != NULL);
                        fprintf(ctx->cFileHandle, INDENT "[UNIFORM_%s_%s] = { PROGRAM_%s, %s, \"%s\" },\n",
                                programName, uniformName, programName, typeName, uniformName);
                }
        }
        fprintf(ctx->cFileHandle, "};\n\n");

        fprintf(ctx->cFileHandle, "const struct SM_AttributeInfo smAttributeInfo[NUM_ATTRIBUTE_KINDS] = {\n");
        for (int programIndex = 0; programIndex < ast->numPrograms; programIndex++) {
                const char *programName = get_aststring_buffer(ast, ast->programDecls[programIndex].programName);
                struct VariableIterator variableIter;
                for (begin_iterating_variables(&variableIter, ast, programIndex);
                        have_variable(&variableIter); go_to_next_variable(&variableIter))
                {
                        struct VariableDecl *decl = get_variable(&variableIter);
                        if (decl->inOrOut != 0) /* TODO: enum for this. 0 == IN direction */
                                continue;
                        { // this code is too complex. It should be easier to determine the shader type.
                                int shaderIndex = ast->linkItems[variableIter.shaderIter.linkIndex].resolvedShaderIndex;
                                int shaderType = ast->shaderDecls[shaderIndex].shaderType;
                                if (shaderType != SHADERTYPE_VERTEX)
                                        continue;  // only vertex shaders can contain attributes. Attributes are "in" variables of the vertex shader.
                        }
                        const char *attribName = get_aststring_buffer(ast, decl->name);
                        int primtypeKind = decl->typeExpr->primtypeKind;
                        const char *typeName = PRIMTYPE_to_GRAFIKATTRIBUTETYPE[primtypeKind];
                        ENSURE(typeName != NULL);
                        fprintf(ctx->cFileHandle, INDENT "[ATTRIBUTE_%s_%s] = { PROGRAM_%s, %s, \"%s\" },\n",
                                programName, attribName, programName, typeName, attribName);
                }
        }
        fprintf(ctx->cFileHandle, "};\n\n");

        fprintf(ctx->hFileHandle,
                "extern GfxShader gfxShader[NUM_SHADER_KINDS];\n"
                "extern GfxProgram gfxProgram[NUM_PROGRAM_KINDS];\n"
                "extern struct SM_LinkDescription smLinkDescription[];\n"
                "extern int numLinkItems;\n"
                "extern GfxUniformLocation gfxUniformLocation[NUM_UNIFORM_KINDS];\n"
                "extern GfxAttributeLocation gfxAttributeLocation[NUM_ATTRIBUTE_KINDS];\n"
                "\n"
        );

        fprintf(ctx->cFileHandle,
                "GfxProgram gfxProgram[NUM_PROGRAM_KINDS];\n"
                "GfxShader gfxShader[NUM_SHADER_KINDS];\n"
                "GfxUniformLocation gfxUniformLocation[NUM_UNIFORM_KINDS];\n"
                "GfxAttributeLocation gfxAttributeLocation[NUM_ATTRIBUTE_KINDS];\n"
                "\n"
        );

        fprintf(ctx->cFileHandle,
                "const struct SM_Description smDescription = {\n"
                INDENT ".programInfo = smProgramInfo,\n"
                INDENT ".shaderInfo = smShaderInfo,\n"
                INDENT ".linkInfo = smLinkInfo,\n"
                INDENT ".uniformInfo = smUniformInfo,\n"
                INDENT ".attributeInfo = smAttributeInfo,\n"
                "\n"
                INDENT ".gfxProgram = gfxProgram,\n"
                INDENT ".gfxShader = gfxShader,\n"
                INDENT ".gfxUniformLocation = gfxUniformLocation,\n"
                INDENT ".gfxAttributeLocation = gfxAttributeLocation,\n"
                "\n"
                INDENT ".numPrograms = NUM_PROGRAM_KINDS,\n"
                INDENT ".numShaders = NUM_SHADER_KINDS,\n"
                INDENT ".numUniforms = NUM_UNIFORM_KINDS,\n"
                INDENT ".numAttributes = NUM_ATTRIBUTE_KINDS,\n"
                INDENT ".numLinks = sizeof smLinkInfo / sizeof smLinkInfo[0],\n"
                "};\n\n"
        );

        for (int programIndex = 0; programIndex < ast->numPrograms; programIndex++) {
                const char *programName = get_aststring_buffer(ast, ast->programDecls[programIndex].programName);
                fprintf(ctx->hFileHandle, "static inline void %sShader_render(GfxVAO vao, int firstVertice, int length) { render_with_GfxProgram(gfxProgram[PROGRAM_%s], vao, firstVertice, length); }\n", programName, programName);
                struct UniformIterator uniformIter;
                for (begin_iterating_uniforms(&uniformIter, ast, programIndex);
                        have_uniform(&uniformIter); go_to_next_uniform(&uniformIter))
                {
                        struct UniformDecl *decl = get_uniform(&uniformIter);
                        const char *uniformName = get_aststring_buffer(ast, decl->uniDeclName);
                        int typeKind = decl->uniDeclTypeExpr->primtypeKind;  //XXX depending on complicated data structure and bad design. There are no "type exprs"
                        fprintf(ctx->hFileHandle, "static inline void %sShader_set_%s", programName, uniformName);
                        const char *fmt;
                        switch (typeKind) {
                        case PRIMTYPE_FLOAT: fmt = "(float x) { set_GfxProgram_uniform_1f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], x); }\n"; break;
                        case PRIMTYPE_VEC2: fmt = "(float x, float y) { set_GfxProgram_uniform_2f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], x, y); }\n"; break;
                        case PRIMTYPE_VEC3: fmt = "(float x, float y, float z) { set_GfxProgram_uniform_3f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], x, y, z); }\n"; break;
                        case PRIMTYPE_VEC4: fmt = "(float x, float y, float z, float w) { set_GfxProgram_uniform_4f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], x, y, z, w); }\n"; break;
                        case PRIMTYPE_MAT2: fmt = "(float *fourFloats) { set_GfxProgram_uniform_mat2f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], fourFloats); }\n"; break;
                        case PRIMTYPE_MAT3: fmt = "(float *nineFloats) { set_GfxProgram_uniform_mat3f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], nineFloats); }\n"; break;
                        case PRIMTYPE_MAT4: fmt = "(float *sixteenFloats) { set_GfxProgram_uniform_mat4f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], sixteenFloats); }\n"; break;
                        default: fatal_f("Not implemented!");
                        }
                        fprintf(ctx->hFileHandle, fmt, programName, programName, uniformName);
                }
        }

        fprintf(ctx->hFileHandle,
                "\n"
                "\n"
                "#ifdef __cplusplus\n\n");
        for (int programIndex = 0; programIndex < ast->numPrograms; programIndex++) {
                const char *programName = get_aststring_buffer(ast, ast->programDecls[programIndex].programName);
                struct UniformIterator uniformIter;
                fprintf(ctx->hFileHandle, "static struct {\n");
                fprintf(ctx->hFileHandle, INDENT "static inline void render(GfxVAO vao, int firstVertice, int length) { render_with_GfxProgram(gfxProgram[PROGRAM_%s], vao, firstVertice, length); }\n", programName);
                for (begin_iterating_uniforms(&uniformIter, ast, programIndex);
                        have_uniform(&uniformIter); go_to_next_uniform(&uniformIter))
                {
                        struct UniformDecl *decl = get_uniform(&uniformIter);
                        const char *uniformName = get_aststring_buffer(ast, decl->uniDeclName);
                        int typeKind = decl->uniDeclTypeExpr->primtypeKind;  //XXX depending on complicated data structure and bad design. There are no "type exprs"
                        fprintf(ctx->hFileHandle, INDENT "static inline void set_%s", uniformName);
                        const char *fmt;
                        switch (typeKind) {
                        case PRIMTYPE_FLOAT: fmt = "(float x) { set_GfxProgram_uniform_1f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], x); }\n"; break;
                        case PRIMTYPE_VEC2: fmt = "(float x, float y) { set_GfxProgram_uniform_2f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], x, y); }\n"; break;
                        case PRIMTYPE_VEC3: fmt = "(float x, float y, float z) { set_GfxProgram_uniform_3f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], x, y, z); }\n"; break;
                        case PRIMTYPE_VEC4: fmt = "(float x, float y, float z, float w) { set_GfxProgram_uniform_4f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], x, y, z, w); }\n"; break;
                        case PRIMTYPE_MAT2: fmt = "(float *fourFloats) { set_GfxProgram_uniform_mat2f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], fourFloats); }\n"; break;
                        case PRIMTYPE_MAT3: fmt = "(float *nineFloats) { set_GfxProgram_uniform_mat3f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], nineFloats); }\n"; break;
                        case PRIMTYPE_MAT4: fmt = "(float *sixteenFloats) { set_GfxProgram_uniform_mat4f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], sixteenFloats); }\n"; break;
                        default: fatal_f("Not implemented!");
                        }
                        fprintf(ctx->hFileHandle, fmt, programName, programName, uniformName);
                }
                fprintf(ctx->hFileHandle, "} %sShader;\n\n", programName);
        }
        fprintf(ctx->hFileHandle, "#endif // #ifdef __cplusplus\n\n");


#if 0
        /* XXX this is really specific to the current setup. Separate stuff out! */
        fprintf(ctx->cFileHandle, "const struct SM_AttributeInfo smAttributeInfo[NUM_ATTRIBUTE_KINDS] = {\n");
        for (int programIndex = 0; programIndex < ast->numPrograms; programIndex++) {
                const char *programName = get_aststring_buffer(ast, ast->programDecls[programIndex].programName);
                struct VariableIterator variableIter;
                for (begin_iterating_variables(&variableIter, ast, programIndex);
                        have_variable(&variableIter); go_to_next_variable(&variableIter))
                {
                        struct VariableDecl *decl = get_variable(&variableIter);
                        if (decl->inOrOut != 0) /* TODO: enum for this. 0 == IN direction */
                                continue;
                        { // this code is too complex. It should be easier to determine the shader type.
                                int shaderIndex = ast->linkItems[variableIter.shaderIter.linkIndex].resolvedShaderIndex;
                                int shaderType = ast->shaderDecls[shaderIndex].shaderType;
                                if (shaderType != SHADERTYPE_VERTEX)
                                        continue;  // only vertex shaders can contain attributes. Attributes are "in" variables of the vertex shader.
                        }
                        const char *attribName = get_aststring_buffer(ast, decl->name);
                        int primtypeKind = decl->typeExpr->primtypeKind;
                        const char *typeName = primtypeKindString[primtypeKind];

                        const char *structName = 

                        fprintf(ctx->cFileHandle, "[ATTRIBUTE_%s_%s] = { PROGRAM_%s, ATTRIBUTE_%s_%s, VAO_%s, VBO_THE_ONE_AND_ONLY, %s, %d, %d }\n",
                                programName, attribName, programName, programName, attribName, programName, typeName, 
                        );
                }
        }
#endif

        fprintf(ctx->hFileHandle,
                "#ifdef __cplusplus\n"
                "} // extern \"C\" {\n"
                "#endif\n"
                "#endif\n");

        fclose(ctx->cFileHandle);
        fclose(ctx->hFileHandle);
}
