#include <glsl-processor/logging.h>
#include <glsl-processor/memoryalloc.h>
#include <glsl-processor/ast.h>
#include <stdarg.h>
#include <stdio.h>
#include <string.h>



#ifdef _MSC_VER
#include <Windows.h>
static void make_directory_if_not_exists(const char *dirpath)
{
        BOOL ret = CreateDirectory(dirpath, NULL);
        if (!ret && GetLastError() != ERROR_ALREADY_EXISTS)
                gp_fatal_f("Failed to create directory %s", dirpath);
}
#else
#include <sys/stat.h>
#include <sys/types.h>
#include <errno.h>
static void make_directory_if_not_exists(const char *dirpath)
{
        int r = mkdir(dirpath, 0770);
        if (r == -1 && errno != EEXIST)
                gp_fatal_f("Failed to create directory %s: %s",
                           dirpath, strerror(errno));
}
#endif

// TODO
#define AUTOGENERATED_DIR "autogenerated/"
#define IFACE_C_FILEPATH AUTOGENERATED_DIR "shaders.c"
#define IFACE_H_FILEPATH AUTOGENERATED_DIR "shaders.h"

#define INDENT "        "

struct MemoryBuffer {
        char *data;
        size_t length;
};

struct MtsCtx {
        struct GP_Ctx *ctx;
        struct MemoryBuffer hFilepath;
        struct MemoryBuffer cFilepath;
        struct MemoryBuffer hFileHandle;
        struct MemoryBuffer cFileHandle;
};

static void commit_to_file(struct MemoryBuffer *mb, const char *filepath)
{
        // writing only if file is different. This is to avoid the IDE unnecessary noticing File changes.
        int different = 0;
        {
                FILE *f = fopen(filepath, "rb");
                if (f == NULL)
                        different = 1;
                else {
                        fseek(f, 0, SEEK_END);
                        long contentsLength = ftell(f);
                        if (contentsLength == -1)
                                gp_fatal_f("Failed to ftell() file '%s': %s", filepath, strerror(errno));
                        if (contentsLength != mb->length)
                                different = 1;
                        else {
                                fseek(f, 0, SEEK_SET);
                                char *contents;
                                ALLOC_MEMORY(&contents, contentsLength + 1);
                                size_t readBytes = fread(contents, 1, contentsLength + 1, f);
                                if (readBytes != contentsLength)
                                        gp_fatal_f("File '%s' seems to have changed during the commit");
                                if (memcmp(contents, mb->data, mb->length) != 0)
                                        different = 1;
                                FREE_MEMORY(&contents);
                        }
                        fclose(f);
                }
        }
        if (different) {
                FILE *f = fopen(filepath, "wb");
                if (f == NULL)
                        gp_fatal_f("Failed to open '%s' for writing", filepath);
                fwrite(mb->data, 1, mb->length, f);
                fflush(f);
                if (ferror(f))
                        gp_fatal_f("I/O error while writing '%s'", filepath);
                fclose(f);
        }
}

static void append_to_buffer_fv(struct MemoryBuffer *mb, const char *fmt, va_list ap)
{
        /* We're not allowed to use "ap" twice, and on gcc using it twice
        actually resulted in a segfault. So we make a backup copy before giving
        it to vsnprintf(). */
        va_list ap2;
        va_copy(ap2, ap);
        size_t need = vsnprintf(NULL, 0, fmt, ap);
        REALLOC_MEMORY(&mb->data, mb->length + need + 1);
        vsnprintf(mb->data + mb->length, need + 1, fmt, ap2);
        mb->data[mb->length + need] = '\0';
        mb->length += need;
}

static void append_to_buffer_f(struct MemoryBuffer *mb, const char *fmt, ...)
{
        va_list ap;
        va_start(ap, fmt);
        append_to_buffer_fv(mb, fmt, ap);
        va_end(ap);
}

static void append_to_buffer(struct MemoryBuffer *mb, const char *data)
{
        append_to_buffer_f(mb, "%s", data);
}

static void append_filepath_component(struct MemoryBuffer *mb, const char *comp)
{
        // TODO: make code more correct, at least for Windows and Linux
        if (!(mb->length == 0 || (mb->data[mb->length - 1] == '/'
#ifdef _MSC_VER
            || mb->data[mb->length - 1] == '\\'
#endif
           ))) {
                append_to_buffer(mb, "/");
        }
        append_to_buffer(mb, comp);
}

static void teardown_buffer(struct MemoryBuffer *mb)
{
        FREE_MEMORY(&mb->data);
        memset(mb, 0, sizeof *mb);
}


static void begin_enum(struct MtsCtx *mts)
{
        append_to_buffer_f(&mts->hFileHandle, "enum {\n");
}

static void end_enum(struct MtsCtx *mts)
{
        append_to_buffer_f(&mts->hFileHandle, "};\n\n");
}

static void add_enum_item(struct MtsCtx *mts, const char *name1)
{
        append_to_buffer_f(&mts->hFileHandle, INDENT "%s,\n", name1);
}

static void add_enum_item_2(struct MtsCtx *mts, const char *name1, const char *name2)
{
        append_to_buffer_f(&mts->hFileHandle, INDENT "%s_%s,\n", name1, name2);
}

static void add_enum_item_3(struct MtsCtx *mts, const char *name1, const char *name2, const char *name3)
{
        append_to_buffer_f(&mts->hFileHandle, INDENT "%s_%s_%s,\n", name1, name2, name3);
}

static const char *const PRIMTYPE_to_GRAFIKATTRIBUTETYPE[GP_NUM_PRIMTYPE_KINDS] = {
        [GP_PRIMTYPE_BOOL] = "GRAFIKATTRTYPE_BOOL",
        [GP_PRIMTYPE_INT] = "GRAFIKATTRTYPE_INT",
        [GP_PRIMTYPE_UINT] = "GRAFIKATTRTYPE_UINT",
        [GP_PRIMTYPE_FLOAT] = "GRAFIKATTRTYPE_FLOAT",
        [GP_PRIMTYPE_DOUBLE] = "GRAFIKUNIFORMTYPE_DOUBLE",
        [GP_PRIMTYPE_VEC2] = "GRAFIKATTRTYPE_VEC2",
        [GP_PRIMTYPE_VEC3] = "GRAFIKATTRTYPE_VEC3",
        [GP_PRIMTYPE_VEC4] = "GRAFIKATTRTYPE_VEC4",
};

static const char *const PRIMTYPE_to_GRAFIKUNIFORMTYPE[GP_NUM_PRIMTYPE_KINDS] = {
        [GP_PRIMTYPE_BOOL] = "GRAFIKUNIFORMTYPE_BOOL",
        [GP_PRIMTYPE_INT] = "GRAFIKUNIFORMTYPE_INT",
        [GP_PRIMTYPE_UINT] = "GRAFIKUNIFORMTYPE_UINT",
        [GP_PRIMTYPE_FLOAT] = "GRAFIKUNIFORMTYPE_FLOAT",
        [GP_PRIMTYPE_DOUBLE] = "GRAFIKUNIFORMTYPE_DOUBLE",
        [GP_PRIMTYPE_VEC2] = "GRAFIKUNIFORMTYPE_VEC2",
        [GP_PRIMTYPE_VEC3] = "GRAFIKUNIFORMTYPE_VEC3",
        [GP_PRIMTYPE_VEC4] = "GRAFIKUNIFORMTYPE_VEC4",
        [GP_PRIMTYPE_MAT2] = "GRAFIKUNIFORMTYPE_MAT2",
        [GP_PRIMTYPE_MAT3] = "GRAFIKUNIFORMTYPE_MAT3",
        [GP_PRIMTYPE_MAT4] = "GRAFIKUNIFORMTYPE_MAT4",
};

void write_c_interface(struct GP_Ctx *ctx, const char *autogenDirpath)
{
        struct MtsCtx mtsCtx = { 0 };
        struct MtsCtx *mts = &mtsCtx;

        append_filepath_component(&mts->hFilepath, autogenDirpath);
        append_filepath_component(&mts->cFilepath, autogenDirpath);
        append_filepath_component(&mts->hFilepath, "shaders.h");
        append_filepath_component(&mts->cFilepath, "shaders.c");

        append_to_buffer_f(&mts->hFileHandle,
                "#ifndef AUTOGENERATED_SHADERS_H_INCLUDED\n"
                "#define AUTOGENERATED_SHADERS_H_INCLUDED\n"
                "\n"
                "#include <glsl-processor.h>\n"
                "\n"
                "#ifdef __cplusplus\n"
                "extern \"C\" {\n"
                "#endif\n"
                "\n");

        begin_enum(mts);
        for (int i = 0; i < ctx->numPrograms; i++)
                add_enum_item_2(mts, "PROGRAM", ctx->programInfo[i].programName);
        add_enum_item(mts, "NUM_PROGRAM_KINDS");
        end_enum(mts);

        begin_enum(mts);
        for (int i = 0; i < ctx->numShaders; i++)
                add_enum_item_2(mts, "SHADER", ctx->shaderInfo[i].shaderName);
        add_enum_item(mts, "NUM_SHADER_KINDS");
        end_enum(mts);

        begin_enum(mts);
        for (int i = 0; i < ctx->numProgramUniforms; i++) {
                int programIndex = ctx->programUniforms[i].programIndex;
                const char *programName = ctx->programInfo[programIndex].programName;
                const char *uniformName = ctx->programUniforms[i].uniformName;
                add_enum_item_3(mts, "UNIFORM", programName, uniformName);
        }
        add_enum_item(mts, "NUM_UNIFORM_KINDS");
        end_enum(mts);

        begin_enum(mts);
        for (int i = 0; i < ctx->numProgramAttributes; i++) {
                int programIndex = ctx->programAttributes[i].programIndex;
                const char *programName = ctx->programInfo[programIndex].programName;
                const char *attributeName = ctx->programAttributes[i].attributeName;
                add_enum_item_3(mts, "ATTRIBUTE", programName, attributeName);
        }
        add_enum_item(mts, "NUM_ATTRIBUTE_KINDS");
        end_enum(mts);

        append_to_buffer_f(&mts->hFileHandle,
                "extern const struct SM_ShaderInfo smShaderInfo[NUM_SHADER_KINDS];\n"
                "extern const struct SM_ProgramInfo smProgramInfo[NUM_PROGRAM_KINDS];\n"
                "extern const struct SM_LinkInfo smLinkInfo[];\n"
                "extern const int numLinkInfos;\n"
                "extern const struct SM_UniformInfo smUniformInfo[NUM_UNIFORM_KINDS];\n"
                "extern const struct SM_AttributeInfo smAttributeInfo[NUM_ATTRIBUTE_KINDS];\n"
                "extern const struct SM_Description smDescription;\n"
                "\n"
        );

        append_to_buffer_f(&mts->cFileHandle, "#include <shaders.h>\n\n");

        append_to_buffer_f(&mts->cFileHandle, "const struct SM_ProgramInfo smProgramInfo[NUM_PROGRAM_KINDS] = {\n");
        for (int i = 0; i < ctx->numPrograms; i++) {
                const char *programName = ctx->programInfo[i].programName;
                append_to_buffer_f(&mts->cFileHandle, INDENT "[PROGRAM_%s] = { \"%s\" },\n", programName, programName);
        }
        append_to_buffer_f(&mts->cFileHandle, "};\n\n");

        append_to_buffer_f(&mts->cFileHandle, "const struct SM_ShaderInfo smShaderInfo[NUM_SHADER_KINDS] = {\n");


#if 0 // TODO: shadef filepath is no longer available. Reorganize file reading!
        for (int i = 0; i < ast->numShaders; i++) {
                struct ShaderInfo *info = &ast->shaderInfo[i];
                char *shaderName = info->shaderName;
                char *shaderFilepath = info->shaderFilepath;
                static const char *const basePath = ""; //XXX
                char *fullyQualifiedFilepath;
                ALLOC_MEMORY(&fullyQualifiedFilepath, strlen(basePath) + strlen(shaderFilepath) + 1);
                memcpy(fullyQualifiedFilepath, basePath, strlen(basePath));
                memcpy(fullyQualifiedFilepath + strlen(basePath), shaderFilepath, strlen(shaderFilepath) + 1);
                int shaderTypeKind = info->shaderType;
                append_to_buffer_f(&ctx->cFileHandle, INDENT "[SHADER_%s] = { %s, \"%s\", \"%s\" },\n",
                        shaderName, shadertypeKindString[shaderTypeKind], shaderName, fullyQualifiedFilepath);
                FREE_MEMORY(&fullyQualifiedFilepath);
        }
#endif
        append_to_buffer_f(&mts->cFileHandle, "};\n\n");
        
        append_to_buffer_f(&mts->cFileHandle, "const struct SM_LinkInfo smLinkInfo[] = {\n");
        for (int i = 0; i < ctx->numLinks; i++) {
                int programIndex = ctx->linkInfo[i].programIndex;
                int shaderIndex = ctx->linkInfo[i].shaderIndex;
                const char *programName = ctx->programInfo[programIndex].programName;
                const char *shaderName = ctx->shaderInfo[shaderIndex].shaderName;
                append_to_buffer_f(&mts->cFileHandle, INDENT "{ PROGRAM_%s, SHADER_%s },\n", programName, shaderName);
        }
        append_to_buffer_f(&mts->cFileHandle, "};\n\n");
        append_to_buffer_f(&mts->cFileHandle, "const int numLinkInfos = sizeof smLinkInfo / sizeof smLinkInfo[0];\n\n");

        append_to_buffer_f(&mts->cFileHandle, "const struct SM_UniformInfo smUniformInfo[NUM_UNIFORM_KINDS] = {\n");

        for (int i = 0; i < ctx->numProgramUniforms; i++) {
                int programIndex = ctx->programUniforms[i].programIndex;
                int primtypeKind = ctx->programUniforms[i].typeKind;
                const char *programName = ctx->programInfo[programIndex].programName;
                const char *uniformName = ctx->programUniforms[i].uniformName;
                const char *typeName = PRIMTYPE_to_GRAFIKUNIFORMTYPE[primtypeKind];
                GP_ENSURE(typeName != NULL);
                append_to_buffer_f(&mts->cFileHandle, INDENT "[UNIFORM_%s_%s] = { PROGRAM_%s, %s, \"%s\" },\n",
                        programName, uniformName, programName, typeName, uniformName);
        }
        append_to_buffer_f(&mts->cFileHandle, "};\n\n");

        append_to_buffer_f(&mts->cFileHandle, "const struct SM_AttributeInfo smAttributeInfo[NUM_ATTRIBUTE_KINDS] = {\n");
        for (int i = 0; i < ctx->numProgramAttributes; i++) {
                int programIndex = ctx->programAttributes[i].programIndex;
                int primtypeKind = ctx->programAttributes[i].typeKind;
                const char *programName = ctx->programInfo[programIndex].programName;
                const char *attributeName = ctx->programAttributes[i].attributeName;
                const char *typeName = PRIMTYPE_to_GRAFIKATTRIBUTETYPE[primtypeKind];
                GP_ENSURE(typeName != NULL);
                append_to_buffer_f(&mts->cFileHandle, INDENT "[ATTRIBUTE_%s_%s] = { PROGRAM_%s, %s, \"%s\" },\n",
                        programName, attributeName, programName, typeName, attributeName);
        }
        append_to_buffer_f(&mts->cFileHandle, "};\n\n");

        append_to_buffer_f(&mts->hFileHandle,
                "extern GfxShader gfxShader[NUM_SHADER_KINDS];\n"
                "extern GfxProgram gfxProgram[NUM_PROGRAM_KINDS];\n"
                "extern GfxUniformLocation gfxUniformLocation[NUM_UNIFORM_KINDS];\n"
                "extern GfxAttributeLocation gfxAttributeLocation[NUM_ATTRIBUTE_KINDS];\n"
                "\n"
        );

        append_to_buffer_f(&mts->cFileHandle,
                "GfxProgram gfxProgram[NUM_PROGRAM_KINDS];\n"
                "GfxShader gfxShader[NUM_SHADER_KINDS];\n"
                "GfxUniformLocation gfxUniformLocation[NUM_UNIFORM_KINDS];\n"
                "GfxAttributeLocation gfxAttributeLocation[NUM_ATTRIBUTE_KINDS];\n"
                "\n"
        );

        append_to_buffer_f(&mts->cFileHandle,
                "const struct SM_Description smDescription = {\n"
                INDENT ".programInfo = smProgramInfo,\n"
                INDENT ".shaderInfo = smShaderInfo,\n"
                INDENT ".linkInfo = smLinkInfo,\n"
                INDENT ".uniformInfo = smUniformInfo,\n"
                INDENT ".attributeInfo = smAttributeInfo,\n"
                "\n"
                INDENT ".gfxProgram = gfxProgram,\n"
                INDENT ".gfxShader = gfxShader,\n"
                INDENT ".gfxUniformLocation = gfxUniformLocation,\n"
                INDENT ".gfxAttributeLocation = gfxAttributeLocation,\n"
                "\n"
                INDENT ".numPrograms = NUM_PROGRAM_KINDS,\n"
                INDENT ".numShaders = NUM_SHADER_KINDS,\n"
                INDENT ".numUniforms = NUM_UNIFORM_KINDS,\n"
                INDENT ".numAttributes = NUM_ATTRIBUTE_KINDS,\n"
                INDENT ".numLinks = sizeof smLinkInfo / sizeof smLinkInfo[0],\n"
                "};\n\n"
        );

        for (int i = 0; i < ctx->numProgramUniforms; i++) {
                int programIndex = ctx->programUniforms[i].programIndex;
                int primtypeKind = ctx->programUniforms[i].typeKind;
                const char *programName = ctx->programInfo[programIndex].programName;
                if (i == 0 || programIndex != ctx->programUniforms[i - 1].programIndex) {
                        append_to_buffer_f(&mts->hFileHandle, "static inline void %sShader_render(GfxVAO vao, int firstVertice, int length) { render_with_GfxProgram(gfxProgram[PROGRAM_%s], vao, firstVertice, length); }\n", programName, programName);
                        append_to_buffer_f(&mts->hFileHandle, "static inline void %sShader_render_primitive(int gfxPrimitiveKind, GfxVAO vao, int firstVertice, int length) { render_primitive_with_GfxProgram(gfxPrimitiveKind, gfxProgram[PROGRAM_%s], vao, firstVertice, length); }\n", programName, programName);
                }
                const char *uniformName = ctx->programUniforms[i].uniformName;
                append_to_buffer_f(&mts->hFileHandle, "static inline void %sShader_set_%s", programName, uniformName);
                const char *fmt;
                switch (primtypeKind) {
                case GP_PRIMTYPE_FLOAT: fmt = "(float x) { set_GfxProgram_uniform_1f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], x); }\n"; break;
                case GP_PRIMTYPE_VEC2: fmt = "(float x, float y) { set_GfxProgram_uniform_2f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], x, y); }\n"; break;
                case GP_PRIMTYPE_VEC3: fmt = "(float x, float y, float z) { set_GfxProgram_uniform_3f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], x, y, z); }\n"; break;
                case GP_PRIMTYPE_VEC4: fmt = "(float x, float y, float z, float w) { set_GfxProgram_uniform_4f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], x, y, z, w); }\n"; break;
                case GP_PRIMTYPE_MAT2: fmt = "(float *fourFloats) { set_GfxProgram_uniform_mat2f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], fourFloats); }\n"; break;
                case GP_PRIMTYPE_MAT3: fmt = "(float *nineFloats) { set_GfxProgram_uniform_mat3f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], nineFloats); }\n"; break;
                case GP_PRIMTYPE_MAT4: fmt = "(float *sixteenFloats) { set_GfxProgram_uniform_mat4f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], sixteenFloats); }\n"; break;
                case GP_PRIMTYPE_SAMPLER2D: continue;  // cannot be set, can it?
                default: gp_fatal_f("Not implemented!");
                }
                append_to_buffer_f(&mts->hFileHandle, fmt, programName, programName, uniformName);
        }

        append_to_buffer_f(&mts->hFileHandle,
                "\n"
                "\n"
                "#ifdef __cplusplus\n\n");
        for (int i = 0; i < ctx->numProgramUniforms; i++) {
                int programIndex = ctx->programUniforms[i].programIndex;
                int primtypeKind = ctx->programUniforms[i].typeKind;
                const char *programName = ctx->programInfo[programIndex].programName;
                const char *uniformName = ctx->programUniforms[i].uniformName;
                if (i == 0 || programIndex != ctx->programUniforms[i - 1].programIndex) {
                        append_to_buffer_f(&mts->hFileHandle, "static struct {\n");
                        append_to_buffer_f(&mts->hFileHandle, INDENT "static inline void render(GfxVAO vao, int firstVertice, int length) { render_with_GfxProgram(gfxProgram[PROGRAM_%s], vao, firstVertice, length); }\n", programName);
                        append_to_buffer_f(&mts->hFileHandle, INDENT "static inline void render_primitive(int gfxPrimitiveKind, GfxVAO vao, int firstVertice, int length) { render_with_GfxProgram(int gfxPrimitiveKind, gfxProgram[PROGRAM_%s], vao, firstVertice, length); }\n", programName);
                }
                append_to_buffer_f(&mts->hFileHandle, INDENT "static inline void set_%s", uniformName);
                const char *fmt;
                switch (primtypeKind) {
                case GP_PRIMTYPE_FLOAT: fmt = "(float x) { set_GfxProgram_uniform_1f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], x); }\n"; break;
                case GP_PRIMTYPE_VEC2: fmt = "(float x, float y) { set_GfxProgram_uniform_2f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], x, y); }\n"; break;
                case GP_PRIMTYPE_VEC3: fmt = "(float x, float y, float z) { set_GfxProgram_uniform_3f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], x, y, z); }\n"; break;
                case GP_PRIMTYPE_VEC4: fmt = "(float x, float y, float z, float w) { set_GfxProgram_uniform_4f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], x, y, z, w); }\n"; break;
                case GP_PRIMTYPE_MAT2: fmt = "(float *fourFloats) { set_GfxProgram_uniform_mat2f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], fourFloats); }\n"; break;
                case GP_PRIMTYPE_MAT3: fmt = "(float *nineFloats) { set_GfxProgram_uniform_mat3f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], nineFloats); }\n"; break;
                case GP_PRIMTYPE_MAT4: fmt = "(float *sixteenFloats) { set_GfxProgram_uniform_mat4f(gfxProgram[PROGRAM_%s], gfxUniformLocation[UNIFORM_%s_%s], sixteenFloats); }\n"; break;
                default: gp_fatal_f("Not implemented!");
                }
                append_to_buffer_f(&mts->hFileHandle, fmt, programName, programName, uniformName);
                if (i + 1 == ctx->numProgramUniforms || programIndex != ctx->programUniforms[i + 1].programIndex)
                        append_to_buffer_f(&mts->hFileHandle, "} %sShader;\n\n", programName);
        }
        append_to_buffer_f(&mts->hFileHandle, "#endif // #ifdef __cplusplus\n\n");


#if 0
        /* XXX this is really specific to the current setup. Separate stuff out! */
        fprintf(ctx->cFileHandle, "const struct SM_AttributeInfo smAttributeInfo[NUM_ATTRIBUTE_KINDS] = {\n");
        for (int programIndex = 0; programIndex < ast->numPrograms; programIndex++) {
                const char *programName = ast->programInfo[programIndex].programName;
                struct VariableIterator variableIter;
                for (begin_iterating_variables(&variableIter, ast, programIndex);
                        have_variable(&variableIter); go_to_next_variable(&variableIter))
                {
                        struct VariableDecl *decl = get_variable(&variableIter);
                        if (decl->inOrOut != 0) /* TODO: enum for this. 0 == IN direction */
                                continue;
                        { // this code is too complex. It should be easier to determine the shader type.
                                int shaderIndex = ast->linkItems[variableIter.shaderIter.linkIndex].resolvedShaderIndex;
                                int shaderType = ast->shaderInfo[shaderIndex].shaderType;
                                if (shaderType != SHADERTYPE_VERTEX)
                                        continue;  // only vertex shaders can contain attributes. Attributes are "in" variables of the vertex shader.
                        }
                        const char *attribName = decl->name;
                        int primtypeKind = decl->typeExpr->primtypeKind;
                        const char *typeName = primtypeKindString[primtypeKind];

                        const char *structName = 

                        fprintf(ctx->cFileHandle, "[ATTRIBUTE_%s_%s] = { PROGRAM_%s, ATTRIBUTE_%s_%s, VAO_%s, VBO_THE_ONE_AND_ONLY, %s, %d, %d }\n",
                                programName, attribName, programName, programName, attribName, programName, typeName, 
                        );
                }
        }
#endif

        append_to_buffer_f(&mts->hFileHandle,
                "#ifdef __cplusplus\n"
                "} // extern \"C\" {\n"
                "#endif\n"
                "#endif\n");


        make_directory_if_not_exists(autogenDirpath);
        commit_to_file(&mts->hFileHandle, mts->hFilepath.data);
        commit_to_file(&mts->cFileHandle, mts->cFilepath.data);

        teardown_buffer(&mts->hFilepath);
        teardown_buffer(&mts->cFilepath);
        teardown_buffer(&mts->hFileHandle);
        teardown_buffer(&mts->cFileHandle);
}
